# Generated by Django 2.1.7 on 2019-03-04 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20190304_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('finish_date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hall', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='show_hall', to='webapp.Hall')),
                ('movie', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='show_movie', to='webapp.Movie')),
            ],
        ),
    ]
