# Generated by Django 2.1.7 on 2019-03-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('finishes_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
