# Generated by Django 2.1.7 on 2019-03-06 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seats', to='webapp.Hall'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='row',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='show',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shows', to='webapp.Hall'),
        ),
        migrations.AlterField(
            model_name='show',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shows', to='webapp.Movie'),
        ),
    ]
