# Generated by Django 2.1.7 on 2019-03-06 18:56

from django.db import migrations, models
import django.db.models.deletion
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20190306_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=webapp.models.generate_code, editable=False, max_length=10, unique_for_date='created_at')),
                ('status', models.CharField(choices=[('created', 'Created'), ('sold', 'Sold'), ('canceled', 'Canceled')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seats', models.ManyToManyField(related_name='booking', to='webapp.Seat')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking', to='webapp.Show')),
            ],
        ),
    ]
