# Generated by Django 2.1.7 on 2019-03-06 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='category',
            new_name='categories',
        ),
    ]
